// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeDashboard.Data;

#nullable disable

namespace SmartHomeDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319151737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Light")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotorSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("PowerValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Quiet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SwingHorizontal")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SwingVertical")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TypeIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("FullDeviceId")
                        .IsUnique();

                    b.HasIndex("RoomId", "DeviceTypeId", "DeviceNumber")
                        .IsUnique();

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8539),
                            Detail = "空调 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 1,
                            FullDeviceId = "living-ac-001",
                            Icon = "fa-wind",
                            IsOn = false,
                            Light = false,
                            Mode = "cool",
                            Name = "客厅空调",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            Quiet = false,
                            RoomId = 1,
                            RoomIdentifier = "living",
                            StatusText = "离线",
                            SwingHorizontal = false,
                            SwingVertical = false,
                            Temperature = 24.0,
                            TypeIdentifier = "ac"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8542),
                            Detail = "灯光 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 2,
                            FullDeviceId = "living-light-001",
                            Icon = "fa-lightbulb",
                            IsOn = false,
                            Name = "客厅灯光",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 1,
                            RoomIdentifier = "living",
                            StatusText = "离线",
                            TypeIdentifier = "light"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8545),
                            Detail = "门锁 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 3,
                            FullDeviceId = "entrance-lock-001",
                            Humidity = 100,
                            Icon = "fa-lock",
                            IsOn = false,
                            Name = "入口门锁",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 7,
                            RoomIdentifier = "entrance",
                            StatusText = "离线",
                            TypeIdentifier = "lock"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8587),
                            Detail = "温度传感器 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 6,
                            FullDeviceId = "kitchen-temp-sensor-001",
                            Icon = "fa-thermometer-half",
                            IsOn = false,
                            Name = "厨房温度传感器",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 4,
                            RoomIdentifier = "kitchen",
                            StatusText = "离线",
                            Temperature = 22.5,
                            TypeIdentifier = "temp-sensor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8590),
                            Detail = "湿度传感器 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 7,
                            FullDeviceId = "bathroom-humidity-sensor-001",
                            Humidity = 65,
                            Icon = "fa-tint",
                            IsOn = false,
                            Name = "浴室湿度传感器",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 5,
                            RoomIdentifier = "bathroom",
                            StatusText = "离线",
                            TypeIdentifier = "humidity-sensor"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8593),
                            Detail = "风扇 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 5,
                            FullDeviceId = "master-bedroom-fan-001",
                            Icon = "fa-fan",
                            IsOn = false,
                            MotorSpeed = 3,
                            Name = "卧室风扇",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 2,
                            RoomIdentifier = "master-bedroom",
                            StatusText = "离线",
                            TypeIdentifier = "fan"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeId")
                        .IsUnique();

                    b.ToTable("DeviceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "智能空调",
                            Icon = "fa-wind",
                            TypeId = "ac",
                            TypeName = "空调"
                        },
                        new
                        {
                            Id = 2,
                            Description = "智能灯泡",
                            Icon = "fa-lightbulb",
                            TypeId = "light",
                            TypeName = "灯光"
                        },
                        new
                        {
                            Id = 3,
                            Description = "智能门锁",
                            Icon = "fa-lock",
                            TypeId = "lock",
                            TypeName = "门锁"
                        },
                        new
                        {
                            Id = 4,
                            Description = "网络摄像头",
                            Icon = "fa-camera",
                            TypeId = "camera",
                            TypeName = "摄像头"
                        },
                        new
                        {
                            Id = 5,
                            Description = "智能风扇",
                            Icon = "fa-fan",
                            TypeId = "fan",
                            TypeName = "风扇"
                        },
                        new
                        {
                            Id = 6,
                            Description = "温度传感器",
                            Icon = "fa-thermometer-half",
                            TypeId = "temp-sensor",
                            TypeName = "温度传感器"
                        },
                        new
                        {
                            Id = 7,
                            Description = "湿度传感器",
                            Icon = "fa-tint",
                            TypeId = "humidity-sensor",
                            TypeName = "湿度传感器"
                        },
                        new
                        {
                            Id = 8,
                            Description = "电机设备",
                            Icon = "fa-cogs",
                            TypeId = "motor",
                            TypeName = "电机"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.RoomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnlineCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8421),
                            Description = "主要活动区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "living",
                            RoomName = "客厅"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8433),
                            Description = "主人卧室",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "master-bedroom",
                            RoomName = "主卧"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8434),
                            Description = "次卧/客房",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "second-bedroom",
                            RoomName = "次卧"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8435),
                            Description = "烹饪区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "kitchen",
                            RoomName = "厨房"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8436),
                            Description = "洗浴区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "bathroom",
                            RoomName = "浴室"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8437),
                            Description = "用餐区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "dining",
                            RoomName = "餐厅"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 19, 23, 17, 37, 438, DateTimeKind.Local).AddTicks(8438),
                            Description = "玄关/入口",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "entrance",
                            RoomName = "入口"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceModel", b =>
                {
                    b.HasOne("SmartHomeDashboard.Models.DeviceTypeModel", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHomeDashboard.Models.RoomModel", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceTypeModel", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.RoomModel", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
