// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeDashboard.Data;

#nullable disable

namespace SmartHomeDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Light")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotorSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("PowerValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Quiet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SwingHorizontal")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SwingVertical")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TypeIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("FullDeviceId")
                        .IsUnique();

                    b.HasIndex("RoomId", "DeviceTypeId", "DeviceNumber")
                        .IsUnique();

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1111),
                            Detail = "空调 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 1,
                            FullDeviceId = "living-ac-001",
                            Icon = "fa-wind",
                            IsOn = false,
                            Light = false,
                            Mode = "cool",
                            Name = "客厅空调",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            Quiet = false,
                            RoomId = 1,
                            RoomIdentifier = "living",
                            StatusText = "离线",
                            SwingHorizontal = false,
                            SwingVertical = false,
                            Temperature = 24.0,
                            TypeIdentifier = "ac"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1115),
                            Detail = "灯光 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 2,
                            FullDeviceId = "living-light-001",
                            Icon = "fa-lightbulb",
                            IsOn = false,
                            Name = "客厅灯光",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 1,
                            RoomIdentifier = "living",
                            StatusText = "离线",
                            TypeIdentifier = "light"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1117),
                            Detail = "门锁 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 3,
                            FullDeviceId = "entrance-lock-001",
                            Humidity = 100,
                            Icon = "fa-lock",
                            IsOn = false,
                            Name = "入口门锁",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 7,
                            RoomIdentifier = "entrance",
                            StatusText = "离线",
                            TypeIdentifier = "lock"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1124),
                            Detail = "温度传感器 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 6,
                            FullDeviceId = "kitchen-temp-sensor-001",
                            Icon = "fa-thermometer-half",
                            IsOn = false,
                            Name = "厨房温度传感器",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 4,
                            RoomIdentifier = "kitchen",
                            StatusText = "离线",
                            Temperature = 22.5,
                            TypeIdentifier = "temp-sensor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1126),
                            Detail = "湿度传感器 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 7,
                            FullDeviceId = "bathroom-humidity-sensor-001",
                            Humidity = 65,
                            Icon = "fa-tint",
                            IsOn = false,
                            Name = "浴室湿度传感器",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 5,
                            RoomIdentifier = "bathroom",
                            StatusText = "离线",
                            TypeIdentifier = "humidity-sensor"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1129),
                            Detail = "风扇 · 等待连接",
                            DeviceNumber = "001",
                            DeviceTypeId = 5,
                            FullDeviceId = "master-bedroom-fan-001",
                            Icon = "fa-fan",
                            IsOn = false,
                            MotorSpeed = 3,
                            Name = "卧室风扇",
                            Power = "0W",
                            PowerValue = 0.0,
                            Progress = 0,
                            ProgressColor = "#a0a0a0",
                            RoomId = 2,
                            RoomIdentifier = "master-bedroom",
                            StatusText = "离线",
                            TypeIdentifier = "fan"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeId")
                        .IsUnique();

                    b.ToTable("DeviceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1071),
                            Description = "智能空调",
                            Icon = "fa-wind",
                            TypeId = "ac",
                            TypeName = "空调"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1073),
                            Description = "智能灯泡",
                            Icon = "fa-lightbulb",
                            TypeId = "light",
                            TypeName = "灯光"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1075),
                            Description = "智能门锁",
                            Icon = "fa-lock",
                            TypeId = "lock",
                            TypeName = "门锁"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1076),
                            Description = "网络摄像头",
                            Icon = "fa-camera",
                            TypeId = "camera",
                            TypeName = "摄像头"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1078),
                            Description = "智能风扇",
                            Icon = "fa-fan",
                            TypeId = "fan",
                            TypeName = "风扇"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1079),
                            Description = "温度传感器",
                            Icon = "fa-thermometer-half",
                            TypeId = "temp-sensor",
                            TypeName = "温度传感器"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1082),
                            Description = "湿度传感器",
                            Icon = "fa-tint",
                            TypeId = "humidity-sensor",
                            TypeName = "湿度传感器"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1083),
                            Description = "电机设备",
                            Icon = "fa-cogs",
                            TypeId = "motor",
                            TypeName = "电机"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.LoginSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFailTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoginIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("LoginSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(912),
                            FailCount = 0,
                            IsEnabled = true,
                            LastLoginIp = "",
                            LoginCount = 0,
                            Password = "123456",
                            PasswordSalt = ""
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.RoomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnlineCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1035),
                            Description = "主要活动区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "living",
                            RoomName = "客厅"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1037),
                            Description = "主人卧室",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "master-bedroom",
                            RoomName = "主卧"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1040),
                            Description = "次卧/客房",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "second-bedroom",
                            RoomName = "次卧"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1042),
                            Description = "烹饪区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "kitchen",
                            RoomName = "厨房"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1046),
                            Description = "洗浴区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "bathroom",
                            RoomName = "浴室"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1048),
                            Description = "用餐区域",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "dining",
                            RoomName = "餐厅"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1049),
                            Description = "玄关/入口",
                            DeviceCount = 0,
                            OnlineCount = 0,
                            RoomId = "entrance",
                            RoomName = "入口"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.SceneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecuteCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecuteTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastExecuteTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepeatDays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SceneName");

                    b.HasIndex("TriggerType");

                    b.ToTable("Scenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actions = "[{\"type\":\"light\",\"action\":\"off\"},{\"type\":\"ac\",\"action\":\"set_temperature\",\"value\":24}]",
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1147),
                            Description = "关闭所有灯光，调整空调温度",
                            ExecuteCount = 0,
                            ExecuteTime = "22:00",
                            Icon = "fa-moon",
                            IsActive = true,
                            RepeatDays = "mon,tue,wed,thu,fri,sat,sun",
                            SceneName = "晚安模式",
                            TriggerCondition = "{\"time\":\"22:00\"}",
                            TriggerType = "time"
                        },
                        new
                        {
                            Id = 2,
                            Actions = "[{\"type\":\"curtain\",\"action\":\"open\"},{\"type\":\"coffee\",\"action\":\"on\"}]",
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1151),
                            Description = "打开卧室窗帘，启动咖啡机",
                            ExecuteCount = 0,
                            ExecuteTime = "07:30",
                            Icon = "fa-sun",
                            IsActive = true,
                            RepeatDays = "mon,tue,wed,thu,fri",
                            SceneName = "晨间唤醒",
                            TriggerCondition = "{\"time\":\"07:30\"}",
                            TriggerType = "time"
                        },
                        new
                        {
                            Id = 3,
                            Actions = "[{\"type\":\"all\",\"action\":\"off\"},{\"type\":\"security\",\"action\":\"on\"}]",
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1155),
                            Description = "关闭所有设备，启动安防系统",
                            ExecuteCount = 0,
                            ExecuteTime = "",
                            Icon = "fa-umbrella-beach",
                            IsActive = false,
                            RepeatDays = "",
                            SceneName = "离家布防",
                            TriggerCondition = "{}",
                            TriggerType = "manual"
                        },
                        new
                        {
                            Id = 4,
                            Actions = "[{\"type\":\"light\",\"action\":\"dim\",\"value\":50},{\"type\":\"music\",\"action\":\"play\",\"playlist\":\"dinner\"}]",
                            CreatedAt = new DateTime(2026, 3, 20, 11, 5, 17, 95, DateTimeKind.Local).AddTicks(1157),
                            Description = "调暗灯光，播放音乐",
                            ExecuteCount = 0,
                            ExecuteTime = "18:00",
                            Icon = "fa-pizza-slice",
                            IsActive = false,
                            RepeatDays = "mon,tue,wed,thu,fri",
                            SceneName = "晚餐模式",
                            TriggerCondition = "{\"time\":\"18:00\"}",
                            TriggerType = "time"
                        });
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.SystemLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LogType");

                    b.HasIndex("Timestamp");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.TcpConnectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConnectedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("FullDeviceId")
                        .IsUnique();

                    b.ToTable("TcpConnections");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceModel", b =>
                {
                    b.HasOne("SmartHomeDashboard.Models.DeviceTypeModel", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHomeDashboard.Models.RoomModel", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.SystemLogModel", b =>
                {
                    b.HasOne("SmartHomeDashboard.Models.DeviceModel", "Device")
                        .WithMany("SystemLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.TcpConnectionModel", b =>
                {
                    b.HasOne("SmartHomeDashboard.Models.DeviceModel", "Device")
                        .WithOne("TcpConnection")
                        .HasForeignKey("SmartHomeDashboard.Models.TcpConnectionModel", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceModel", b =>
                {
                    b.Navigation("SystemLogs");

                    b.Navigation("TcpConnection");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.DeviceTypeModel", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SmartHomeDashboard.Models.RoomModel", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
